#以下配置全部是从nacos配置中心读取的


spring:
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 362623
    url: jdbc:mysql://192.168.200.131:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  #cloud:
    #alicloud:
      #access-key: *  #生成的Accesskey子用户信息
      #secret-key: *
      #oss:
        #endpoint: http://oss-cn-qingdao.aliyuncs.com  #开通的oss服务的外网访问地址
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #指定返回日期的格式

  session:
    store-type: redis #指定使用redis来保存session数据
    redis:
      namespace: spring:session #存储的命名空间

  redis:  #配置redis
    host: 192.168.200.132
    port: 6379

  cache:
    type: redis #配置使用redis作为缓存
    redis:
      time-to-live: 3600000 #设置1个小时的存活时间
      key-prefix: SpringCache_  #每个缓存空间的前缀
      use-key-prefix: true  #是否使用缓存前缀
      cache-null-values: true   #是否使用缓存空值，防止缓存穿透

  thymeleaf:
    cache: false #关闭页面缓存

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #mapper文件位置
  global-config:
    db-config:
      id-type: auto #表示使用数据库主键自增
      logic-delete-field: show_status  #全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)


#打印sql日志
logging:
  level:
    gulimall:
      product:
        dao: debug

#暴露配置端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#配置我们自定义的线程池参数，想在配置文件中获得提示需要引入spring-boot-configuration-processor依赖
gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
