#以下配置全部是从nacos配置中心读取的


spring:
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 362623
    url: jdbc:mysql://192.168.200.131:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  #cloud:
    #alicloud:
      #access-key: *  #生成的Accesskey子用户信息
      #secret-key: *
      #oss:
        #endpoint: http://oss-cn-qingdao.aliyuncs.com  #开通的oss服务的外网访问地址
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #指定返回日期的格式

  redis:  #配置redis
    host: 192.168.200.132
    port: 6379

  #关闭页面缓存
  thymeleaf:
    cache: false

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #mapper文件位置
  global-config:
    db-config:
      id-type: auto #表示使用数据库主键自增
      logic-delete-field: show_status  #全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

#打印sql日志
logging:
  level:
    gulimall:
      product:
        dao: debug

#暴露配置端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
