#以下配置全部是从nacos配置中心读取的


spring:
  session:
    store-type: redis #指定使用redis来保存session数据
    redis:
      namespace: spring:session #存储的命名空间
  thymeleaf:
    cache: false #关闭页面缓存
  redis:    #配置redis
    host: 192.168.200.132
    port: 6379

#打印sql日志
logging:
  level:
    gulimall:
      product:
        dao: debug