#以下配置全部是从nacos配置中心读取的


spring:
  session:
    store-type: redis #指定使用redis来保存session数据
    redis:
      namespace: spring:session #存储的命名空间
  thymeleaf:
    cache: false #关闭页面缓存
  redis:    #配置redis
    host: 192.168.200.132
    port: 6379

#打印sql日志
logging:
  level:
    gulimall:
      product:
        dao: debug

#配置我们自定义的线程池参数，想在配置文件中获得提示需要引入spring-boot-configuration-processor依赖
gulimall:
  thread:
    keep-alive-time: 10
    core-pool-size: 20
    maximum-pool-size: 200

seata:
  enabled: true
  application-id: gulimall-shopping-cart #服务唯一id,使用当前服务名称即可
  tx-service-group: my_test_tx_group #service.vgroupMapping后面跟着的名字
  enable-auto-data-source-proxy: true #自动数据源代理
  config: #配置中心的相关配置
    type: nacos
    nacos:
      namespace: 8168949a-6a7a-48ac-b12d-8866fa941b01
      serverAddr: 192.168.200.199
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry: #注册中心相关配置
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.200.199
      namespace:
      userName: "nacos"
      password: "nacos"