#以下配置全部是从nacos配置中心读取的


spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080  #sentinel控制台地址
        port: 8719  #指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer,#默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #指定返回日期的格式

  redis:  #配置redis
    host: 192.168.200.132
    port: 6379

  thymeleaf:
    cache: false #关闭页面缓存

  zipkin:
    base-url: http://192.168.200.132:9411 #zipkin服务器地址
    discovery-client-enabled: false #关闭服务发现,否则SpringCloud会把zipkin的url当做服务名称
    sender:
      type: web #设置使用web的方式传送数据
  sleuth:
    sampler:
      probability: 1 #设置抽样采集率为100%,默认0.1即10%

  session:
    store-type: redis #指定使用redis来保存session数据
    redis:
      namespace: spring:session #存储的命名空间

  task:
    execution:
      pool:
        core-size: 20 #配置使用 @Async注解 异步任务的核心线程数
        max-size: 200 #最大线程数
        queue-capacity: 10000 #队列最大容纳数

  #配置RabbitMQ
  rabbitmq:
    host: 192.168.200.132
    port: 5672
    virtual-host: /gulimall #虚拟主机名称
    username: admin
    password: 362623
    publisher-confirm-type: simple  #开启消息发送到服务端确认回调
    publisher-returns: true #开启消息抵达队列返回回调
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnConfirm
    listener:
      simple:
        acknowledge-mode: manual  #开始手动确认消息

#打印sql日志
logging:
  level:
    gulimall:
      seckill:
        dao: debug

#暴露所有端点,actuator健康监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true #开启feign对sentinel的支持