#以下配置全部是从nacos配置中心读取的


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes: #路由路径精确的要向前放
        - id: gulimall-product
          uri: lb://gulimall-product  #匹配后提供服务的路由地址,服务名称(lb开头，则会开启负载均衡)
          predicates:
            - Path=/api/product/**   #断言,路径相匹配的进行路由
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}  #重写路径

        - id: gulimall-third-party
          uri: lb://gulimall-third-party   #gulimall-third-party服务
          predicates:
            - Path=/api/thirdparty/**   #前端项目发起的请求单独带api
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}  #重写路径

        - id: gulimall-member
          uri: lb://gulimall-member   #gulimall-member服务
          predicates:
            - Path=/api/member/**   #前端项目发起的请求单独带api路径
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}  #重写路径

        - id: gulimall-ware
          uri: lb://gulimall-ware   #gulimall-ware服务
          predicates:
            - Path=/api/ware/**   #前端项目发起的请求单独带api路径
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}  #重写路径

        - id: renern-fast
          uri: lb://renern-fast   #renren-fast服务
          predicates:
            - Path=/api/**   #前端项目发起的请求只带带api路径则默认路由到renern-fast
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}  #重写路径带上/renren-fast

        - id: gulimall-host
          uri: lb://gulimall-product  #匹配后提供服务的路由地址,服务名称(lb开头，则会开启负载均衡)
          predicates:
            - Host=192.168.200.199  #根据请求头传送的host进行路由