##以下配置全部是从nacos配置中心读取的
#
#
#spring:
#  cloud:
#    alicloud:
#      access-key: *  #生成的Accesskey子用户信息
#      secret-key: *
#      oss:
#        endpoint: oss-cn-qingdao.aliyuncs.com  #开通的oss服务的外网访问地址
#        bucket: sunqixin-gulimal  #自定义的配置
#      #配置发送短信需要的各种信息，自定义的配置字段
#      sms:
#        host: http://feginesms.market.alicloudapi.com
#        path: /codeNotice
#        sign: 1
#        skin: 13
#        appcode: *

seata:
  enabled: true
  application-id: gulimall-third-party #服务唯一id,使用当前服务名称即可
  tx-service-group: gulimall-third-party-group #service.vgroupMapping后面跟着的名字
  enable-auto-data-source-proxy: true #自动数据源代理
  config: #配置中心的相关配置
    type: nacos
    nacos:
      namespace: 8168949a-6a7a-48ac-b12d-8866fa941b01
      serverAddr: 192.168.200.199
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry: #注册中心相关配置
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.200.199
      namespace:
      userName: "nacos"
      password: "nacos"
