#以下配置全部是从nacos配置中心读取的


spring:
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 362623
    url: jdbc:mysql://192.168.200.131:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  #配置RabbitMQ
  rabbitmq:
    host: 192.168.200.132
    port: 5672
    virtual-host: /gulimall #虚拟主机名称
    username: admin
    password: 362623
    publisher-confirm-type: simple  #开启消息发送到服务端确认回调
    publisher-returns: true #开启消息抵达队列返回回调
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnConfirm
    listener:
      simple:
        acknowledge-mode: manual  #开始手动确认消息

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #mapper文件位置
  global-config:
    db-config:
      id-type: auto #表示使用数据库主键自增

#打印sql日志
logging:
  level:
    gulimall:
      ware:
        dao: debug

#暴露配置端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

seata:
  enabled: true
  application-id: gulimall-ware #服务唯一id,使用当前服务名称即可
  tx-service-group: gulimall-ware-group #service.vgroupMapping后面跟着的名字
  enable-auto-data-source-proxy: true #自动数据源代理
  config: #配置中心的相关配置
    type: nacos
    nacos:
      namespace: 8168949a-6a7a-48ac-b12d-8866fa941b01
      serverAddr: 192.168.200.199
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry: #注册中心相关配置
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.200.199
      namespace:
      userName: "nacos"
      password: "nacos"