#以下配置全部是从nacos配置中心读取的


spring:
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 362623
    url: jdbc:mysql://192.168.200.131:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #mapper文件位置
  global-config:
    db-config:
      id-type: auto #表示使用数据库主键自增

#打印sql日志
logging:
  level:
    gulimall:
      ware:
        dao: debug

#暴露配置端点
management:
  endpoints:
    web:
      exposure:
        include: '*'